set title
set titlestring=VIM:\ %-25.55F\ %a%r%m titlelen=70

" Automatic vim-plug install
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  silent !mkdir -p ~/.vim/autoload
  silent !ln -s ~/.local/share/nvim/site/autoload/plug.vim ~/.vim/autoload/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.local/share/nvim/plugged')
  Plug 'tpope/vim-repeat'
  Plug 'tpope/vim-commentary'
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'
  Plug 'VundleVim/Vundle.vim'
  Plug 'airblade/vim-gitgutter'
  Plug 'mxw/vim-jsx'
  Plug 'terryma/vim-multiple-cursors'
  Plug 'tpope/vim-fugitive'
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'chriskempson/base16-vim'
  Plug 'nathanaelkane/vim-indent-guides'
  Plug 'pangloss/vim-javascript'
  Plug 'tpope/vim-surround'
call plug#end()

" swapfiles in ~/.vim/swap
set directory^=$HOME/.vim/swap/

filetype plugin indent on

nnoremap <silent> <Leader>l :nohl<CR>
vnoremap <Leader>s :sort<CR>

set softtabstop=2 expandtab shiftwidth=2 tabstop=2

" Statusline
" %F - Longer path
" %r readonly flag
" %m modified flag
" %y filetype
" %c column
" %l line
" %L number of lines
" %P percentage through buffer
" %= right side
set statusline=%F%r%m\ %y%=%{fugitive#head()}\ 0x%B\ %c\ %l/%L\ %P

" Highlight all search results
set hlsearch

" Search while typing
set incsearch

" UTF-8
if &modifiable
    set encoding=utf-8
    set fileencoding=utf-8
    set fileencodings=utf-8
endif

" Hilight current line
set cursorline

" Hilight line 80
set fo-=t
set colorcolumn=80
highlight ColorColumn ctermbg=5

" Longer undo history
set undolevels=20000

" Yank to system clipboard (PRIMARY)
set clipboard=unnamedplus

" Don't require .jsx extension for jsx syntax
let g:jsx_ext_required = 0

" Hide gitgutter and line numbers and toggle with f12
let g:gitgutter_enabled = 0
map <F12> :set number!<CR>:GitGutterToggle<CR>
inoremap <F12> <Esc>:set number!<CR>:GitGutterToggle<CR>i

" Make multi cursors less annoying
let g:multi_cursor_exit_from_insert_mode = 0
let g:multi_cursor_exit_from_visual_mode = 0

set ignorecase
set smartcase

imap <up> <nop>
imap <down> <nop>
imap <right> <nop>
imap <left> <nop>

" Q wraps paragraph
vmap Q gq
nmap Q gqap

" Toggle paste mode (no auto indent) with f2
set pastetoggle=<f2>

set nowrap

" Center cursor vertically
set scrolloff=999

" Colors
let base16colorspace=256
colorscheme base16-default-dark 

" Indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let g:indent_guides_auto_colors = 1
set wildignore+=*bower_components,node_modules,webroot,tmp

" Activate jsx support for .js files
let g:jsx_ext_required = 0

" jklö instead of hjkl
noremap ; l
noremap ö l
noremap l k
noremap k j
noremap j h

" Arrow keys to resize splits
map <Up> <C-W>+
map <Down> <C-W>-
map <Left> <C-W><
map <Right> <C-W>>

" ctrl-p to search files with fzf
nnoremap <c-p> :Files!<cr>

" ,r to search file contents with rg + fzf
nnoremap <leader>r :Rg!<cr>

" :Files with preview
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview('up:70%'), <bang>0)

" :Rg with preview
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview('up:70%'),
  \   <bang>0)
