set title
set titlestring=VIM:\ %-25.55F\ %a%r%m titlelen=70

" Required for vundle
set nocompatible
filetype off
set shell=/bin/bash

" Automatic Vundle install
let firstRun=0
let vundle_readme=expand('~/.vim/bundle/Vundle.vim/README.md')
if !filereadable(vundle_readme)
  echo "Installing Vundle.."
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  let firstRun=1
endif
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'mxw/vim-jsx'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-fugitive'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'chriskempson/base16-vim'
Plugin 'nathanaelkane/vim-indent-guides'

if firstRun == 1
  echo "Installing Bundles, please ignore key map error messages"
  :PluginInstall
endif

" swapfiles in ~/.vim/swap
set directory^=$HOME/.vim/swap/

filetype plugin indent on

nnoremap <silent> <Leader>l :nohl<CR>
vnoremap <Leader>s :sort<CR>

set softtabstop=2 expandtab shiftwidth=2 tabstop=2

" Statusline
" %F - Longer path
" %r readonly flag
" %m modified flag
" %y filetype
" %c column
" %l line
" %L number of lines
" %P percentage through buffer
" %= right side
set statusline=%F%r%m\ %y%=%{fugitive#head()}\ 0x%B\ %c\ %l/%L\ %P

" Highlight all search results
set hlsearch

" Search while typing
set incsearch

" UTF-8
if &modifiable
    set encoding=utf-8
    set fileencoding=utf-8
    set fileencodings=utf-8
endif

" Hilight current line
set cursorline

" Hilight line 80
set fo-=t
set colorcolumn=80
highlight ColorColumn ctermbg=5

" Longer undo history
set undolevels=20000

" Yank to system clipboard (PRIMARY)
set clipboard=unnamedplus

" Don't require .jsx extension for jsx syntax
let g:jsx_ext_required = 0

" Hide gitgutter and line numbers and toggle with f12
let g:gitgutter_enabled = 0
map <F12> :set number!<CR>:GitGutterToggle<CR>
inoremap <F12> <Esc>:set number!<CR>:GitGutterToggle<CR>i

" Make multi cursors less annoying
let g:multi_cursor_exit_from_insert_mode = 0
let g:multi_cursor_exit_from_visual_mode = 0

set ignorecase
set smartcase

imap <up> <nop>
imap <down> <nop>
imap <right> <nop>
imap <left> <nop>

" Q wraps paragraph
vmap Q gq
nmap Q gqap

" Toggle paste mode (no auto indent) with f2
set pastetoggle=<f2>

set nowrap

" Center cursor vertically
set scrolloff=999

" Colors
let base16colorspace=256
colorscheme base16-default-dark 

" Indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let g:indent_guides_auto_colors = 1
set wildignore+=*bower_components,node_modules,webroot,tmp

" Activate jsx support for .js files
let g:jsx_ext_required = 0
